capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),
    path('attach/<int:project_id>/', views.attach, name="attach"),
    path('image/<int:wireframe_id>/', views.image, name="image"),
    path('profile/<int:profile_id>/', views.profile, name="profile"),
    path('projects/', views.projects, name="projects"),
    path('projects/<int:project_id>/', views.project, name="project"),
    path('projects/<int:project_id>/sprints/', views.sprints, name="sprints"),
    path('projects/<int:project_id>/sprints/<int:sprint_id>/', views.sprint, name="sprint"),
    path('projects/<int:project_id>/sprints/<int:sprint_id>/tasks', views.tasks, name='tasks'),
    path('projects/<int:project_id>/sprints/<int:sprint_id>/tasks/<int:task_id>', views.task, name='task'),
    path('projects/<int:project_id>/pages/', views.pages, name="pages"),
    path('projects/<int:project_id>/pages/<int:page_id>/', views.page, name="page"),
    path('projects/<int:project_id>/pages/<int:page_id>/wireframes/', views.wireframes, name="wireframes"),
    path('projects/<int:project_id>/pages/<int:page_id>/wireframe/<int:wireframe_id>/', views.wireframe, name="wireframe"),
    path('togglecomplete/<int:task_id>/', views.toggle_complete, name="togglecomplete")
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

TYPES = (
    ('client', 'Client'),
    ('dev', 'Developer')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, unique=True)
    user_type = models.CharField(max_length=10, choices=TYPES)

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Project(models.Model):
    client = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="client", null=True, blank=True)
    dev = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="dev")
    title = models.CharField(max_length=50)

class Page(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)

class Wireframe(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='wireframe_images/')
    description = models.TextField(max_length=200)

class Sprint(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    @property
    def completed(self):
        tasks = self.task_set.all()
        for task in tasks:
            if not task.completed:
                return False
        return True

class Task(models.Model):
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE)
    description = models.TextField(max_length=200)
    completed = models.BooleanField(default=False)

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Project, Sprint, Page, Task, Wireframe, Profile

TYPES = (
    ('client', 'Client'),
    ('dev', 'Developer')
)

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=25)
    user_type = forms.ChoiceField(choices=TYPES)

class ProjectForm(forms.ModelForm):
    client_email = forms.CharField(max_length=50, required=False)
    class Meta:
        model = Project
        fields = ['title']

class EditProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title']

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['title']

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['description']

class WireframeForm(forms.ModelForm):
    class Meta:
        model = Wireframe
        fields = ['image', 'description']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['full_name', 'email']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.db.models import Q
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Project, Sprint, Task, Page, Wireframe, Profile
from .forms import RegistrationForm, ProjectForm, PageForm, TaskForm, WireframeForm, ProfileForm, EditProjectForm
import json


def home(request):
    if request.user.is_authenticated:
        return redirect(projects)
    context = {'register_form': RegistrationForm(prefix="register"), 'login_form': AuthenticationForm(prefix="login")}
    try:
        context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
    except:
        pass
    return render(request, 'home.html', context)

def login(request):
    if request.method == 'POST': # Authenticate Login\
        print(request.POST)
        form = AuthenticationForm(request.POST, prefix="login")
        username = request.POST.get('login-username')
        password = request.POST.get('login-password')
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth_login(request, user)
            if 'project' in request.POST:
                project = Project.objects.get(id=request.POST.get('project'))
                project.client = user.profile
                project.save()
            return redirect('/')
        context = {'login_form': form, 'register_form': RegistrationForm(prefix="register"), 'login_error': 'true'}
        try:
            context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
        except:
            pass
        if 'project' in request.POST:
            context['project_id'] = request.POST.get('project')
            return render(request, 'attach.html', context)
        return render(request, 'home.html', context)
    else:
        return render(request, '404.html')

def signup(request):
    email_error = False
    if request.method == 'POST': #Authenticate registration
        form = RegistrationForm(request.POST, prefix="register")
        if form.is_valid():
            first = request.POST.get('register-first_name')
            last = request.POST.get('register-last_name')
            email = request.POST.get('register-email')
            user_type = request.POST.get('register-user_type')
            username = request.POST.get('register-username')
            password = request.POST.get('register-password1')
            try:
                profile = Profile.objects.get(email=email)
                if 'profile' in request.POST:
                    return render(request, 'attach.html', {'login_form': AuthenticationForm(prefix="login"), 'register_form': form, 'register_error': 'true', 'project_id': request.POST.get('project'), 'email_error': 'true'})
                else:
                    return render(request, 'home.html', {'login_form': AuthenticationForm(prefix="login"), 'register_form': form, 'register_error': 'true'})
            except:
                pass
            user = form.save()
            user.profile.full_name = f"{first} {last}"
            user.profile.email = email
            user.profile.user_type = user_type
            user.save()
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            if 'project' in request.POST:
                project = Project.objects.get(id=request.POST.get('project'))
                project.client = user.profile
                project.save()
            return redirect('/')
        context = {'login_form': AuthenticationForm(prefix="login"), 'register_form': form, 'register_error': 'true'}
        try:
            context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
        except:
            pass
        if 'project' in request.POST:
            context = {'login_form': AuthenticationForm(prefix="login"), 'register_form': form, 'register_error': 'true', 'project_id': request.POST.get('project')}
            return render(request, 'attach.html', context)
        return render(request, 'home.html', context)
    else: 
        return render(request, '404.html')

@login_required
def logout(request):
    auth_logout(request)
    return redirect(home)

def attach(request, project_id):
    context = {'register_form': RegistrationForm(prefix="register"), 'login_form': AuthenticationForm(prefix="login"), 'project_id': project_id}
    return render(request, 'attach.html', context)

@login_required
def image(request, wireframe_id):
    try: # Render full size image page
        wireframe = Wireframe.objects.get(id=wireframe_id)
        return render(request, 'image.html', {'wireframe': wireframe})
    except: # If broken link
        return render(request, '404.html')

@login_required
def profile(request, profile_id):
    if request.method == 'POST' and request.POST.get('_method') == 'PUT': # Update Profile
        profile = Profile.objects.get(id=profile_id)
        if request.user.profile != profile:
            return redirect(home)
        ProfileForm(request.POST, prefix="profile", instance=profile).save()
    return redirect(home)

@login_required
def projects(request):
    error = False
    if request.method == 'POST' and request.user.profile.user_type == 'dev': # Projects Create
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.dev = request.user.profile
            # TODO: Attach to client if email. If not return a unique link to give to the client
            try: # This checks if the email given is valid
                client = Profile.objects.get(email=request.POST.get("client_email"))
                project.client = client
                project.save()
                return redirect(f'/projects/{project.id}/')
            except:
                project.save()
                return redirect(f'/projects/{project.id}/')
        error = True
    else:
        form = ProjectForm()
    projects = Project.objects.filter(Q(client=request.user.profile) | Q(dev=request.user.profile))
    context = {'register_form': RegistrationForm(prefix="register"), 'login_form': AuthenticationForm(prefix="login"), 'profile_form': ProfileForm(prefix="profile"), 'projects': projects, 'form': form}
    if error:
        context['create_error'] = 'true'
    context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
    return render(request, 'projects/index.html', context)

@login_required
def project(request, project_id):
    if request.method == 'GET': # Project Show
        try:
            project = Project.objects.get(id=project_id)
            context = {'register_form': RegistrationForm(prefix="register"), 'login_form': AuthenticationForm(prefix="login"), 'project': project, 'page_form': PageForm(), 'project_form': EditProjectForm(instance=project)}
            try:
                context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
            except:
                pass
            return render(request, 'projects/show.html', context)
        except Exception as e:
            print(e)
            return render(request, '404.html')
    elif request.method == 'POST' and request.POST.get('_method') == 'PUT' and request.user.profile.user_type == 'client': # Project Update
        project = Project.objects.get(id=project_id)
        form = EditProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
        return redirect(f'/projects/{project_id}/')
    elif request.method == 'POST' and request.POST.get('_method') == 'DELETE' and request.user.profile.user_type == 'client': # Project Delete
        project = Project.objects.get(id=project_id)
        project.delete()
        return redirect(projects)
    else:
        return render(request, '404.html')

@login_required
def sprints(request, project_id):
    if request.method == 'POST' and request.user.profile.user_type == 'client': # Sprints Create
        try:
            sprint = Sprint(project=Project.objects.get(id=project_id))
            sprint.save()
            return redirect(f'/projects/{project_id}/sprints/{sprint.id}')
        except:
            return redirect(project, project_id)
    else:
        return render(request, '404.html')

@login_required
def sprint(request, project_id, sprint_id):
    if request.method == 'GET': # Sprint Show
        try:
            sprint = Sprint.objects.get(id=sprint_id)
            project = sprint.project
            for x, s in enumerate(project.sprint_set.all()):
                if s.id == sprint.id:
                    break
            context = {'register_form': RegistrationForm(prefix="register"), 'login_form': AuthenticationForm(prefix="login"), 'sprint': sprint, 'task_form': TaskForm(), 'number': x + 1}
            try:
                context['profile_form'] = ProfileForm(instance=request.user.profile, prefix="profile")
            except:
                pass
            return render(request, 'projects/sprints/show.html', context)
        except Exception as e:
            print(e)
            return render(request, '404.html')
    elif request.method == 'POST' and request.POST.get('_method') == 'DELETE' and request.user.profile.user_type == 'client': # TODO: Sprint Delete
        sprint = Sprint.objects.get(id=sprint_id)
        sprint.delete()
        return redirect(f'/projects/{project_id}/')
    else:
        return render(request, '404.html')

@login_required
def tasks(request, project_id, sprint_id):
    if request.method == 'POST' and request.user.profile.user_type == 'client': # Task Create

main_app/templates/projects/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} WePortal Projects {% endblock %}

{% block styles %} 
    <link rel="stylesheet" href="{% static 'styles/projects/index.css' %}">
{% endblock %}

{% block scripts %}
   <script src="{% static 'scripts/projects/index.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="uk-container">
        <ul class="uk-breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><span>My Projects</span></li>
        </ul>
        {% if user.profile.user_type == 'dev' %}
            <button class="add-btn" uk-toggle="target: #new-project-form">+</button>
        {%endif%}
        <h1 class="uk-heading-medium uk-heading-divider uk-text-center">My Projects</h1>
        <div class="projects uk-flex uk-flex-column">
            {% for project in projects %}
                <div class="project uk-flex" data-url="{% url 'project' project.id %}">
                    <img src="{% static '' %}{{project.page_set.all.0.wireframe_set.all.0.image}}{% if not project.page_set.all.0.wireframe_set.all.0.image %}wireframe_images/default.png {%endif%}" alt="">
                    <h1 class="uk-heading-medium project-title uk-flex-1 uk-text-center">{{project.title}}</h1>
                    <span class="user">{% if user.profile.user_type == 'client' %}{{project.dev.full_name}}{%else%}{{project.client.full_name}}{%endif%}</span>
                </div>
            {% endfor %}
        </div>

        <div {% if create_error %} class="uk-open" style="display: block;" {% endif %} id="new-project-form" uk-modal>
            <div class="uk-modal-body uk-modal-dialog">
                <button class="uk-modal-close-default" uk-close></button>
                <h2 class="uk-modal-title">Create New Project</h2>
                <form action="{% url 'projects' %}" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="uk-button uk-button-primary form-button" type="submit" value="Create Project"></input>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

main_app/templates/projects/show.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} WePortal Project {% endblock %}

{% block styles %} 
    <link rel="stylesheet" href="{% static 'styles/projects/show.css' %}">
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        let userType = "{{user.profile.user_type}}";
    </script>
    <script src="{% static 'scripts/projects/show.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="uk-container">
        <ul class="uk-breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'projects' %}">My Projects</a></li>
            <li><span>{{project.title}}</span></li>
        </ul>
        {% if not project.client %}
            <span id='url-span'>
                Client URL: 
                <input type="text" name="url" id="url" value="weportal-nb.herokuapp.com/attach/{{project.id}}" disabled>
                <button class="uk-button uk-button-text" id="copy">Copy</button>
            </span>
        {% endif %}
        <h1 class="project-title uk-heading-medium uk-heading-divider uk-text-center">
            {{project.title}}
            {% if user.profile.user_type == 'client' %}
                <a class="project-edit" uk-icon="icon: pencil; ratio: 1.5" href="#" uk-toggle="target: #edit-project-form"></a>
                <a class="project-delete" uk-icon="icon: trash; ratio: 1.5" href="#" uk-toggle="target: #delete-project-form"></a>
            {% endif %}
        </h1>

        <div class="sprints uk-flex" uk-grid>
            <div class="uk-width-1-3 uk-width-1-4@m titles">
                <h1 class="uk-heading-small light">Sprints</h1>
                <button class="uk-button uk-button-text light" uk-toggle="target: #new-sprint-form">New Sprint</button>
            </div>
            <div class="uk-width-2-3 uk-width-3-4@m uk-flex" uk-overflow-auto>
                {% for sprint in project.sprint_set.all %}
                    <div class="sprint uk-card-hover {% if sprint.completed %}completed{%endif%}" data-url="{% url 'sprint' project.id sprint.id %}">
                        <h1 class="uk-heading-small">Sprint {{forloop.counter}}</h1>
                        <p>Completed? <input type="checkbox" disabled></p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="pages uk-flex" uk-grid>
            <div class="uk-width-1-3 uk-width-1-4@m titles">
                <h1 class="uk-heading-small light">Pages</h1>
                <button class='uk-button uk-button-text light' uk-toggle="target: #new-page-form">New Page</button>
            </div>
            <div class="uk-width-2-3 uk-width-3-4@m uk-flex" uk-overflow-auto>
                {% for page in project.page_set.all %}
                    <div class="page uk-card-hover" data-url="{% url 'page' project.id page.id %}">
                        <h1 class="uk-heading-small light">{{page.title}}</h1>
                        <img src="{% static '' %}{% if page.wireframe_set.all.0.image %}{{page.wireframe_set.all.0.image}}{%else%}wireframe_images/default.png{%endif%}" alt="">
                    </div>
                {% endfor %}
            </div>
        </div>

        <div id="new-sprint-form" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">
                <button class="uk-modal-close-default" uk-close></button>
                <h2 class="uk-modal-title">Create New Sprint?</h2>
                <form id="sprint-form" action="{% url 'sprints' project.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit"id="new-sprint" class="uk-button uk-button-primary form-button" value="Create Sprint">
                </form>
            </div>
        </div>

        <div id="new-page-form" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">
                <button class="uk-modal-close-default" uk-close></button>
                <h2 class="uk-modal-title">Create New Page</h2>
                <form action="{% url 'pages' project.id %}" method="POST">
                    {% csrf_token %}
                    {{ page_form|crispy }}
                    <input class="uk-button uk-button-primary form-button" type="submit" value="Create Page">
                </form>
            </div>
        </div>

         <div id="edit-project-form" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">
                <button class="uk-modal-close-default" uk-close></button>
                <h2 class="uk-modal-title new-title">Edit Project</h2>
                <form id="form" action="{% url 'project' project.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="_method" value="PUT">
                    {{project_form|crispy}}
                    <input class="uk-button uk-button-primary form-button" id="submit" type="submit" value="Update">
                </form>
            </div>
        </div>

        <div id="delete-project-form" uk-modal>
            <div class="uk-modal-dialog uk-modal-body">
                <button class="uk-modal-close-default" uk-close></button>
                <h2 class="uk-modal-title new-title">Delete Project</h2>
                Delete this project and all sprints and pages with which it is associated?
                <form id="form" action="{% url 'project' project.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="_method" value="DELETE">
                    <input class="uk-button uk-button-danger form-button" id="submit" type="submit" value="Delete">
                </form>
            </div>
        </div>

    </div>
{% endblock %}